// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApiFiscal.Dominio.Model
{
    [Table("FISCALNCM_MONOFASICO")]
    public partial class FiscalncmMonofasico
    {
        [Key]
        [Column("ID_FISCALNCM_MONOFASICO")]
        public int IdFiscalncmMonofasico { get; set; }
        [Column("TEC")]
        [StringLength(10)]
        public string Tec { get; set; }
        [Column("NOMETEC")]
        [StringLength(60)]
        public string Nometec { get; set; }
        [Column("CST_PIS_SAIDA")]
        [StringLength(3)]
        public string CstPisSaida { get; set; }
        [Column("CST_COFINS_SAIDA")]
        [StringLength(3)]
        public string CstCofinsSaida { get; set; }
        [Column("PPIS", TypeName = "money")]
        public decimal? Ppis { get; set; }
        [Column("PCOFINS", TypeName = "money")]
        public decimal? Pcofins { get; set; }
        [Column("VPIS", TypeName = "money")]
        public decimal? Vpis { get; set; }
        [Column("VCOFINS", TypeName = "money")]
        public decimal? Vcofins { get; set; }
        [Column("DATA_HORA_MODIFICACAO", TypeName = "smalldatetime")]
        public DateTime? DataHoraModificacao { get; set; }
        [Column("PIS_ENTRADA", TypeName = "money")]
        public decimal? PisEntrada { get; set; }
        [Column("COFINS_ENTRADA", TypeName = "money")]
        public decimal? CofinsEntrada { get; set; }
    }
}