// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApiFiscal.Dominio.Model
{
    [Keyless]
    public partial class Fiscalcfopview
    {
        [Column("CST_ICMS")]
        [StringLength(2)]
        public string CstIcms { get; set; }
        [Column("CST_IPI")]
        [StringLength(2)]
        public string CstIpi { get; set; }
        [Column("CST_PIS")]
        [StringLength(2)]
        public string CstPis { get; set; }
        [Column("CST_COFINS")]
        [StringLength(2)]
        public string CstCofins { get; set; }
        [Column("NATUREZA")]
        [StringLength(255)]
        public string Natureza { get; set; }
        [Column("CalculaICMS")]
        [StringLength(1)]
        public string CalculaIcms { get; set; }
        [Column("CalculaIPI")]
        [StringLength(1)]
        public string CalculaIpi { get; set; }
        [Column("CalculaPIS")]
        [StringLength(1)]
        public string CalculaPis { get; set; }
        [Column("CalculaCOFINS")]
        [StringLength(1)]
        public string CalculaCofins { get; set; }
        [Column("CLAFISCAL")]
        [StringLength(5)]
        public string Clafiscal { get; set; }
    }
}