// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApiFiscal.Dominio.Model
{
    [Table("TBL_Empresa")]
    [Index(nameof(Codmarca), Name = "CODMARCA")]
    [Index(nameof(Codpla), Name = "CODPLA")]
    [Index(nameof(GrupoEmpresarial), Name = "GrupoEmpresarial")]
    [Index(nameof(GrupoEmpresa), Name = "IX_GrupoEmpresaID")]
    [Index(nameof(Loja), Name = "IX_LOJA")]
    [Index(nameof(Loja), Name = "IX_LOJA_MARCA")]
    [Index(nameof(Loja), Name = "IX_LojaID")]
    [Index(nameof(Codmarca), Name = "IX_MARCA_LOJA")]
    [Index(nameof(TblEmpresaId), Name = "IX_TBL_EMPRESA_ID")]
    [Index(nameof(Loja), Name = "LOJA", IsUnique = true)]
    public partial class TblEmpresa
    {
        [Key]
        [Column("TBL_EMPRESA_ID")]
        public int TblEmpresaId { get; set; }
        [Column("TStamp")]
        public byte[] Tstamp { get; set; }
        [Column("LOJA")]
        [StringLength(3)]
        public string Loja { get; set; }
        [Column("NOME")]
        [StringLength(100)]
        public string Nome { get; set; }
        [Column("RUA")]
        [StringLength(34)]
        public string Rua { get; set; }
        [Column("NUMERO")]
        public int? Numero { get; set; }
        [Column("COD_IBGE_UF")]
        [StringLength(2)]
        public string CodIbgeUf { get; set; }
        [StringLength(22)]
        public string Complemento { get; set; }
        [Column("BAIRRO")]
        [StringLength(40)]
        public string Bairro { get; set; }
        [Column("CEP")]
        [StringLength(9)]
        public string Cep { get; set; }
        [Column("CIDADE")]
        [StringLength(40)]
        public string Cidade { get; set; }
        [Column("ESTADO")]
        [StringLength(2)]
        public string Estado { get; set; }
        [Column("FONE")]
        [StringLength(20)]
        public string Fone { get; set; }
        [Column("FAX")]
        [StringLength(20)]
        public string Fax { get; set; }
        [Column("CGC")]
        [StringLength(18)]
        public string Cgc { get; set; }
        [Column("IE")]
        [StringLength(30)]
        public string Ie { get; set; }
        [Column("INSC_MUN")]
        [StringLength(20)]
        public string InscMun { get; set; }
        [Column("SEQUENCIA")]
        [StringLength(8)]
        public string Sequencia { get; set; }
        [Column("PAGE")]
        public int? Page { get; set; }
        [Column("PART_0", TypeName = "money")]
        public decimal? Part0 { get; set; }
        [Column("PART_1", TypeName = "money")]
        public decimal? Part1 { get; set; }
        [Column("PART_2", TypeName = "money")]
        public decimal? Part2 { get; set; }
        [Column("PART_3", TypeName = "money")]
        public decimal? Part3 { get; set; }
        [Column("PART_4", TypeName = "money")]
        public decimal? Part4 { get; set; }
        [Column("PART_5", TypeName = "money")]
        public decimal? Part5 { get; set; }
        [Column("PART_6", TypeName = "money")]
        public decimal? Part6 { get; set; }
        [Column("PART_7", TypeName = "money")]
        public decimal? Part7 { get; set; }
        [Column("AREA")]
        public short? Area { get; set; }
        [Column("TIPOLOJA")]
        [StringLength(1)]
        public string Tipoloja { get; set; }
        [Column("NFS_UltimaNota")]
        public int? NfsUltimaNota { get; set; }
        [Column("NFS_UltimaData", TypeName = "smalldatetime")]
        public DateTime? NfsUltimaData { get; set; }
        [Column("U_MAPA")]
        [StringLength(4)]
        public string UMapa { get; set; }
        [Column("NFE_UltimaNota")]
        public int? NfeUltimaNota { get; set; }
        [Column("NFE_UltimaData", TypeName = "smalldatetime")]
        public DateTime? NfeUltimaData { get; set; }
        [Column("NFE_Modelo")]
        [StringLength(2)]
        public string NfeModelo { get; set; }
        [Column("NFE_Serie")]
        [StringLength(3)]
        public string NfeSerie { get; set; }
        [Column("NFS_Modelo")]
        [StringLength(2)]
        public string NfsModelo { get; set; }
        [Column("NFS_Serie")]
        [StringLength(3)]
        public string NfsSerie { get; set; }
        [Column("NFM_UltimaNota")]
        public int? NfmUltimaNota { get; set; }
        [Column("NFM_UltimaData", TypeName = "smalldatetime")]
        public DateTime? NfmUltimaData { get; set; }
        [Column("NFM_Modelo")]
        [StringLength(2)]
        public string NfmModelo { get; set; }
        [Column("NFM_Serie")]
        [StringLength(3)]
        public string NfmSerie { get; set; }
        [Column("GRP_PRC")]
        [StringLength(2)]
        public string GrpPrc { get; set; }
        [Column("PAGEENT")]
        public int? Pageent { get; set; }
        [Column("PAGESAI")]
        public int? Pagesai { get; set; }
        [Column("PAGECX")]
        public int? Pagecx { get; set; }
        [Column("NUMSER1")]
        [StringLength(20)]
        public string Numser1 { get; set; }
        [Column("NUMSER2")]
        [StringLength(20)]
        public string Numser2 { get; set; }
        [Column("NUMSER3")]
        [StringLength(20)]
        public string Numser3 { get; set; }
        [Column("NUMSER4")]
        [StringLength(20)]
        public string Numser4 { get; set; }
        [Column("LC_DATA_MINIMA", TypeName = "smalldatetime")]
        public DateTime? LcDataMinima { get; set; }
        [Column("LC_DATA_MAXIMA", TypeName = "smalldatetime")]
        public DateTime? LcDataMaxima { get; set; }
        [Column("LE_DATA_MINIMA", TypeName = "smalldatetime")]
        public DateTime? LeDataMinima { get; set; }
        [Column("LE_DATA_MAXIMA", TypeName = "smalldatetime")]
        public DateTime? LeDataMaxima { get; set; }
        [Column("LS_DATA_MINIMA", TypeName = "smalldatetime")]
        public DateTime? LsDataMinima { get; set; }
        [Column("LS_DATA_MAXIMA", TypeName = "smalldatetime")]
        public DateTime? LsDataMaxima { get; set; }
        [Column("ALIQICMS", TypeName = "smallmoney")]
        public decimal? Aliqicms { get; set; }
        [Column("GRUPO_EMPRESA")]
        [StringLength(1)]
        public string GrupoEmpresa { get; set; }
        [Column("GRUPO")]
        [StringLength(2)]
        public string Grupo { get; set; }
        [Column("FANTASIA")]
        [StringLength(50)]
        public string Fantasia { get; set; }
        [Column("IMUNICIPAL")]
        [StringLength(20)]
        public string Imunicipal { get; set; }
        [Column("CNAE")]
        [StringLength(9)]
        public string Cnae { get; set; }
        [Column("EMAIL")]
        [StringLength(50)]
        public string Email { get; set; }
        [Column("ESTABELECIMENTO")]
        [StringLength(1)]
        public string Estabelecimento { get; set; }
        [Column("ATUALIZADO_WEB")]
        [StringLength(1)]
        public string AtualizadoWeb { get; set; }
        [Column("ATIVADO")]
        [StringLength(1)]
        public string Ativado { get; set; }
        [Column("GR_SUPERVISOR")]
        [StringLength(2)]
        public string GrSupervisor { get; set; }
        [Column("IPADDRESS")]
        [StringLength(15)]
        public string Ipaddress { get; set; }
        [Column("NFE_Especie")]
        [StringLength(4)]
        public string NfeEspecie { get; set; }
        [Column("NFM_Especie")]
        [StringLength(3)]
        public string NfmEspecie { get; set; }
        [Column("NFS_Especie")]
        [StringLength(3)]
        public string NfsEspecie { get; set; }
        [Column("OBS")]
        [StringLength(1000)]
        public string Obs { get; set; }
        [Column("CODMARCA")]
        [StringLength(5)]
        public string Codmarca { get; set; }
        [Column("SUPERSIMPLES")]
        [StringLength(1)]
        public string Supersimples { get; set; }
        [Column("cat52_usuario")]
        [StringLength(20)]
        public string Cat52Usuario { get; set; }
        [Column("cat52_senha")]
        [StringLength(20)]
        public string Cat52Senha { get; set; }
        [Column("COD_IBGE_MUN")]
        [StringLength(7)]
        public string CodIbgeMun { get; set; }
        [Column("FORMATONFE")]
        [StringLength(1)]
        public string Formatonfe { get; set; }
        [Column("COD_IBGE_PAIS")]
        [StringLength(4)]
        public string CodIbgePais { get; set; }
        [Column("IDpais")]
        public int? Idpais { get; set; }
        [Column("IEST")]
        [StringLength(20)]
        public string Iest { get; set; }
        [Column("PorcPIS", TypeName = "smallmoney")]
        public decimal? PorcPis { get; set; }
        [Column(TypeName = "smallmoney")]
        public decimal? PorcCofins { get; set; }
        [StringLength(10)]
        public string GrupoEmpresarial { get; set; }
        [StringLength(1)]
        public string RegimeTributario { get; set; }
        [Column("pPIS", TypeName = "smallmoney")]
        public decimal? PPis { get; set; }
        [Column("pCOFINS", TypeName = "smallmoney")]
        public decimal? PCofins { get; set; }
        [Column("perfilsped")]
        [StringLength(1)]
        public string Perfilsped { get; set; }
        [StringLength(1)]
        public string IndAtividade { get; set; }
        [Column("CODPLA")]
        [StringLength(10)]
        public string Codpla { get; set; }
        [Column("NUMERO_SUFRAMA")]
        [StringLength(11)]
        public string NumeroSuframa { get; set; }
        [Column("Email_NFE")]
        [StringLength(200)]
        public string EmailNfe { get; set; }
        [Column("Email_NFeServiços")]
        [StringLength(200)]
        public string EmailNfeServiços { get; set; }
        [Column("NFE")]
        [StringLength(10)]
        public string Nfe { get; set; }
        [Column("SCAN_ATIVADO")]
        [StringLength(1)]
        public string ScanAtivado { get; set; }
        [Column("scan_justificativa")]
        [StringLength(60)]
        public string ScanJustificativa { get; set; }
        [Column("data_contingencia", TypeName = "date")]
        public DateTime? DataContingencia { get; set; }
        [Column("ContribuinteIPI")]
        [StringLength(1)]
        public string ContribuinteIpi { get; set; }
        [Column("modNFE")]
        [StringLength(2)]
        public string ModNfe { get; set; }
        [Column("serNFE")]
        [StringLength(3)]
        public string SerNfe { get; set; }
        [Column("SIGLA")]
        [StringLength(4)]
        public string Sigla { get; set; }
        [Column("SIGLAEMPRESA")]
        [StringLength(4)]
        public string Siglaempresa { get; set; }
        [Column("CAMINHO")]
        [StringLength(10)]
        public string Caminho { get; set; }
        [Column("espNFE")]
        [StringLength(5)]
        public string EspNfe { get; set; }
        [Column("LRLP")]
        [StringLength(1)]
        public string Lrlp { get; set; }
        [Column("modNFEA")]
        [StringLength(2)]
        public string ModNfea { get; set; }
        [Column("modNFEB")]
        [StringLength(2)]
        public string ModNfeb { get; set; }
        [Column("serNFEA")]
        [StringLength(3)]
        public string SerNfea { get; set; }
        [Column("serNFEB")]
        [StringLength(3)]
        public string SerNfeb { get; set; }
        [Column("espNFEA")]
        [StringLength(3)]
        public string EspNfea { get; set; }
        [Column("espNFEB")]
        [StringLength(3)]
        public string EspNfeb { get; set; }
        [Column("NFE_UltimaNotaA")]
        public int? NfeUltimaNotaA { get; set; }
        [Column("NFE_UltimaNotaB")]
        public int? NfeUltimaNotaB { get; set; }
        [Column("NFE_UltimaDataA", TypeName = "smalldatetime")]
        public DateTime? NfeUltimaDataA { get; set; }
        [Column("NFE_UltimaDataB", TypeName = "smalldatetime")]
        public DateTime? NfeUltimaDataB { get; set; }
        [Column("nfe_contigencia_numero")]
        public int? NfeContigenciaNumero { get; set; }
        [Column("nfe_contigencia_serie")]
        public int? NfeContigenciaSerie { get; set; }
        [Column("nire")]
        [StringLength(11)]
        public string Nire { get; set; }
        [StringLength(100)]
        public string AtividadeEconomica { get; set; }
        [Column("Email_Gerente")]
        [StringLength(50)]
        public string EmailGerente { get; set; }
        public int? Perfil { get; set; }
        [Column("DATABLOQUEIO", TypeName = "smalldatetime")]
        public DateTime? Databloqueio { get; set; }
        [Column("LANCADO")]
        [StringLength(2)]
        public string Lancado { get; set; }
        [Column("TIPO_POS")]
        [StringLength(10)]
        public string TipoPos { get; set; }
        [Required]
        [StringLength(1)]
        public string VarejoOutlet { get; set; }
        [Column("FONE_SAC")]
        [StringLength(20)]
        public string FoneSac { get; set; }
        [Column("token")]
        [StringLength(70)]
        public string Token { get; set; }
        [StringLength(50)]
        public string Apelido { get; set; }
        [Column("COD_IBGE_REGIAO")]
        public int? CodIbgeRegiao { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? DataAberturaLoja { get; set; }
        [StringLength(100)]
        public string SaleChannel { get; set; }
        [Column("merchantName")]
        [StringLength(200)]
        public string MerchantName { get; set; }
        [Required]
        [StringLength(1)]
        public string GeraBalancete { get; set; }
        public int? PrazoEntrega { get; set; }
        [Required]
        public bool? GeraMovtosTransferencia { get; set; }
        [StringLength(200)]
        public string ApelidoCoachTopline { get; set; }
        [Column("PorcISS", TypeName = "smallmoney")]
        public decimal? PorcIss { get; set; }
        [Column("CodigoISS")]
        [StringLength(5)]
        public string CodigoIss { get; set; }
        public bool? NaoConferirCompras { get; set; }
        [Column("codigoFornecedor")]
        [StringLength(10)]
        public string CodigoFornecedor { get; set; }
        [Column("naoincideST")]
        public bool? NaoincideSt { get; set; }
        [StringLength(1)]
        public string PossueIsencao { get; set; }
        [StringLength(200)]
        public string ProcessoIsencaoPisCofins { get; set; }
        [Column("nfe_contigencia_Modelo")]
        [StringLength(5)]
        public string NfeContigenciaModelo { get; set; }
        [Column("nfe_contigencia_Especie")]
        [StringLength(5)]
        public string NfeContigenciaEspecie { get; set; }
        [Column("NFE_UltimaNota_C")]
        public int? NfeUltimaNotaC { get; set; }
        [Column("NFE_UltimaData_C", TypeName = "date")]
        public DateTime? NfeUltimaDataC { get; set; }
        [Column("NFE_Modelo_C")]
        [StringLength(5)]
        public string NfeModeloC { get; set; }
        [Column("NFE_Serie_C")]
        [StringLength(5)]
        public string NfeSerieC { get; set; }
        [Column("NFE_Especie_c")]
        [StringLength(5)]
        public string NfeEspecieC { get; set; }
        [Column("Emitente_NFE")]
        [StringLength(1)]
        public string EmitenteNfe { get; set; }
        [Column("CELULAR")]
        [StringLength(20)]
        public string Celular { get; set; }
        [StringLength(10)]
        public string AccountNumberCoachTopline { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DataEncerramentoLoja { get; set; }
        public int? FlagGeraMovtoTerceiro { get; set; }
    }
}