// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApiFiscal.Dominio.Model
{
    [Table("TBL_ICMS_UF")]
    public partial class TblIcmsUf
    {
        [Column("UF_Origem")]
        [StringLength(2)]
        public string UfOrigem { get; set; }
        [Column("UF_Destino")]
        [StringLength(2)]
        public string UfDestino { get; set; }
        [Column("ALIQICMS_INTERNA", TypeName = "money")]
        public decimal? AliqicmsInterna { get; set; }
        [Column("ALIQICMS_EXTERNA", TypeName = "money")]
        public decimal? AliqicmsExterna { get; set; }
        [Column("ALIQICMS_IMPORT", TypeName = "money")]
        public decimal? AliqicmsImport { get; set; }
        [Column("OBS1")]
        [StringLength(100)]
        public string Obs1 { get; set; }
        [Column("OBS2")]
        [StringLength(100)]
        public string Obs2 { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? DataInicio { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? DataTermino { get; set; }
        [Key]
        [Column("ID_ICMS_UF")]
        public int IdIcmsUf { get; set; }
    }
}