// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApiFiscal.Dominio.Model
{
    [Keyless]
    public partial class ViewProdutoGeralNomesAntigosComCodBarras
    {
        [Column("descricaotamanho")]
        [StringLength(100)]
        public string Descricaotamanho { get; set; }
        [Column("Produto_ID")]
        public long ProdutoId { get; set; }
        [Column("ProdutoColecaoID")]
        public int? ProdutoColecaoId { get; set; }
        [Column("lin_nom")]
        [StringLength(100)]
        public string LinNom { get; set; }
        [Column("lin_numero")]
        public int? LinNumero { get; set; }
        [StringLength(100)]
        public string DescricaoLinha { get; set; }
        [Column("ProdutoFamiliaID")]
        public int? ProdutoFamiliaId { get; set; }
        [Column("familia")]
        [StringLength(100)]
        public string Familia { get; set; }
        [Column("ProdutoSubGrupoID")]
        public int? ProdutoSubGrupoId { get; set; }
        [StringLength(255)]
        public string DescricaoSubGrupo { get; set; }
        [Column("ProdutoSubDivisaoID")]
        public int? ProdutoSubDivisaoId { get; set; }
        [Column("subdivisao")]
        [StringLength(255)]
        public string Subdivisao { get; set; }
        [Column("ProdutoGeneroID")]
        public int? ProdutoGeneroId { get; set; }
        [Column("publico")]
        [StringLength(100)]
        public string Publico { get; set; }
        [Column("ProdutoCorID")]
        public int? ProdutoCorId { get; set; }
        [Column("cor_descricao")]
        [StringLength(100)]
        public string CorDescricao { get; set; }
        [Column("comitem")]
        [StringLength(10)]
        public string Comitem { get; set; }
        [StringLength(100)]
        public string Apelido { get; set; }
        [StringLength(100)]
        public string DetalheCor { get; set; }
        [Column("ProdutoTierID")]
        public int? ProdutoTierId { get; set; }
        [Column("tier")]
        [StringLength(100)]
        public string Tier { get; set; }
        [Column("ProdutoUnidadeMedidaID")]
        public int? ProdutoUnidadeMedidaId { get; set; }
        [Column("unidade")]
        [StringLength(5)]
        public string Unidade { get; set; }
        [Column("ProdutoCategoriaID")]
        public int? ProdutoCategoriaId { get; set; }
        [Column("categoria")]
        [StringLength(100)]
        public string Categoria { get; set; }
        [Column("ref_nom")]
        [StringLength(500)]
        public string RefNom { get; set; }
        [Column("rctl")]
        [StringLength(25)]
        public string Rctl { get; set; }
        [Column("refitem")]
        [StringLength(50)]
        public string Refitem { get; set; }
        [Column("tamitem")]
        [StringLength(5)]
        public string Tamitem { get; set; }
        [Column("descr_ingles")]
        [StringLength(500)]
        public string DescrIngles { get; set; }
        [Column("descr_port")]
        [StringLength(500)]
        public string DescrPort { get; set; }
        [Column("DESC_EXPORTACAO")]
        [StringLength(500)]
        public string DescExportacao { get; set; }
        [StringLength(500)]
        public string DescricaoEcommerce { get; set; }
        [StringLength(10)]
        public string TamanhoConvertido { get; set; }
        [Column("peso", TypeName = "decimal(10, 3)")]
        public decimal? Peso { get; set; }
        [Column("prod_peso", TypeName = "decimal(10, 3)")]
        public decimal? ProdPeso { get; set; }
        [Column("prod_altura", TypeName = "decimal(10, 3)")]
        public decimal? ProdAltura { get; set; }
        [Column("prod_largura", TypeName = "decimal(10, 3)")]
        public decimal? ProdLargura { get; set; }
        [Column("prod_comprimento", TypeName = "decimal(10, 3)")]
        public decimal? ProdComprimento { get; set; }
        [StringLength(30)]
        public string Profundidade { get; set; }
        [StringLength(10)]
        public string FatorConversao { get; set; }
        [StringLength(100)]
        public string Lavagem { get; set; }
        [StringLength(500)]
        public string Composicao { get; set; }
        [Column("MarcaID")]
        public int? MarcaId { get; set; }
        [Column("codmarca")]
        [StringLength(5)]
        public string Codmarca { get; set; }
        [Column("codforn")]
        public int Codforn { get; set; }
        [Column("marca")]
        [StringLength(20)]
        public string Marca { get; set; }
        [Column("descr_ecf")]
        [StringLength(29)]
        public string DescrEcf { get; set; }
        public short? StatusProduto { get; set; }
        public long? CodigoOperacao { get; set; }
        [Column("ProdutoGrupoID")]
        public int? ProdutoGrupoId { get; set; }
        [StringLength(255)]
        public string DescricaoGrupo { get; set; }
        [Column("ProdutoDivisaoID")]
        public int? ProdutoDivisaoId { get; set; }
        [Column("divisao")]
        [StringLength(255)]
        public string Divisao { get; set; }
        [Column("data", TypeName = "smalldatetime")]
        public DateTime? Data { get; set; }
        [Column("pcusto")]
        public int Pcusto { get; set; }
        [Required]
        [Column("licenca")]
        [StringLength(1)]
        public string Licenca { get; set; }
        [Column("tec")]
        [StringLength(10)]
        public string Tec { get; set; }
        [StringLength(13)]
        public string Cbarras { get; set; }
        [Column("cst")]
        public int Cst { get; set; }
        [Required]
        [Column("fantasia")]
        [StringLength(1)]
        public string Fantasia { get; set; }
        [Column("pv_interno")]
        public int PvInterno { get; set; }
        [Required]
        [Column("usuario")]
        [StringLength(1)]
        public string Usuario { get; set; }
        [Required]
        [Column("atualizado")]
        [StringLength(1)]
        public string Atualizado { get; set; }
        [Column("ipi", TypeName = "money")]
        public decimal? Ipi { get; set; }
        [StringLength(5)]
        public string Processo { get; set; }
        [Required]
        [Column("LARGURA_DETALHE")]
        [StringLength(1)]
        public string LarguraDetalhe { get; set; }
        [Column("QTDE")]
        public int? Qtde { get; set; }
        [Column("icms", TypeName = "money")]
        public decimal? Icms { get; set; }
        [Column("PC_ImpImport", TypeName = "money")]
        public decimal? PcImpImport { get; set; }
        [Column("FOBLIQ")]
        public int Fobliq { get; set; }
        [Column("pvenda1a", TypeName = "money")]
        public decimal Pvenda1a { get; set; }
        [Column("D_ULT1A", TypeName = "smalldatetime")]
        public DateTime DUlt1a { get; set; }
        [Column("pliqa", TypeName = "money")]
        public decimal Pliqa { get; set; }
        [Column("D_LIQA", TypeName = "smalldatetime")]
        public DateTime DLiqa { get; set; }
        [Column("ORIGEM")]
        public byte? Origem { get; set; }
        [Column("ORIGEM_LOJA")]
        public byte? OrigemLoja { get; set; }
        [Column("ANO")]
        public int? Ano { get; set; }
        [Column("ESTACAO")]
        public int? Estacao { get; set; }
        [Column("ACABA")]
        public int? Acaba { get; set; }
        [Column("PRUNIT")]
        public int? Prunit { get; set; }
        [Column("CODACAB")]
        public int? Codacab { get; set; }
        [Column("DGERACAO")]
        public int? Dgeracao { get; set; }
        [Column("PVENDA1B")]
        public int? Pvenda1b { get; set; }
        [Column("PVENDA1C")]
        public int? Pvenda1c { get; set; }
        [Column("PVENDA2A")]
        public int? Pvenda2a { get; set; }
        [Column("PVENDA2B")]
        public int? Pvenda2b { get; set; }
        [Column("DCUSTO1")]
        public int? Dcusto1 { get; set; }
        [Column("PVENDA2C")]
        public int? Pvenda2c { get; set; }
        [Column("PLIQB")]
        public int? Pliqb { get; set; }
        [Column("PLIQC")]
        public int? Pliqc { get; set; }
        [Column("D_ULT1B")]
        public int? DUlt1b { get; set; }
        [Column("D_ULT1C")]
        public int? DUlt1c { get; set; }
        [Column("D_LIQB")]
        public int? DLiqb { get; set; }
        [Column("D_LIQC")]
        public int? DLiqc { get; set; }
        [Column("PCUICM")]
        public int? Pcuicm { get; set; }
        [Column("PMEDIO")]
        public int? Pmedio { get; set; }
        [Column("PMINIMO")]
        public int? Pminimo { get; set; }
        [Column("CONDICAO1")]
        public int? Condicao1 { get; set; }
        [Column("CONDICAO2")]
        public int? Condicao2 { get; set; }
        [Column("MARKUP_A")]
        public int? MarkupA { get; set; }
        [Column("MARKUP_B")]
        public int? MarkupB { get; set; }
        [Column("MARKUP_C")]
        public int? MarkupC { get; set; }
        [Column("EXISTE")]
        public int? Existe { get; set; }
        [Column("CODCICLO")]
        public int? Codciclo { get; set; }
        [Column("SUBCATEGORIA")]
        public int? Subcategoria { get; set; }
        [Column("USUARIOPV")]
        public int? Usuariopv { get; set; }
        [Column("USUARIOPC")]
        public int? Usuariopc { get; set; }
        [Column("FOB_EURO")]
        public int? FobEuro { get; set; }
        [Column("OBS")]
        public int? Obs { get; set; }
        [Column("PACKS")]
        public int? Packs { get; set; }
        [Column("KIT")]
        public int? Kit { get; set; }
        [Column("PM_ComPIS")]
        public int? PmComPis { get; set; }
        [Column("PM_SemPIS")]
        public int? PmSemPis { get; set; }
        [Column("PC_SemPIS")]
        public int? PcSemPis { get; set; }
        [Column("PC_ComPIS")]
        public int? PcComPis { get; set; }
        [Column("PM_Gerencial")]
        public int? PmGerencial { get; set; }
        [Column("MOEDA")]
        public int? Moeda { get; set; }
        [Column("PCUSTO2")]
        public int? Pcusto2 { get; set; }
        [Column("DCUSTO2")]
        public int? Dcusto2 { get; set; }
        [Column("PMEDIOUNIT")]
        public int? Pmediounit { get; set; }
        [Column("D_ULT2A")]
        public int? DUlt2a { get; set; }
        [Column("D_ULT2B")]
        public int? DUlt2b { get; set; }
        [Column("D_ULT2C")]
        public int? DUlt2c { get; set; }
        [Column("DESC_TAM")]
        public int? DescTam { get; set; }
        [Column("COD_GRUPO")]
        public int? CodGrupo { get; set; }
        [Column("DESC_GRUPO")]
        public int? DescGrupo { get; set; }
        [Column("COD_COMPANIA")]
        public int? CodCompania { get; set; }
        [Column("NOME_COMPANIA")]
        public int? NomeCompania { get; set; }
        [Column("TECIDO")]
        public int? Tecido { get; set; }
        [Column("C_TEMP")]
        public int? CTemp { get; set; }
        [Column("TEMPORADA")]
        public int? Temporada { get; set; }
        [Column("PC_Cofins")]
        public int? PcCofins { get; set; }
        [Column("PC_IPI")]
        public int? PcIpi { get; set; }
        [Column("PC_PisPasep")]
        public int? PcPisPasep { get; set; }
        public int? Fabric { get; set; }
        [Column("CTBINT")]
        public int? Ctbint { get; set; }
        [Column("CODPLA")]
        public int? Codpla { get; set; }
        [Column("TIPOSPED")]
        public int? Tiposped { get; set; }
        [Column("GRUPOSPED")]
        public int? Gruposped { get; set; }
        public long? QtdMinEstoque { get; set; }
        [Column("CEST")]
        [StringLength(10)]
        public string Cest { get; set; }
    }
}