// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApiFiscal.Dominio.Model
{
    [Keyless]
    public partial class VwUfFcppadrao
    {
        [Column("UFID")]
        public int Ufid { get; set; }
        [StringLength(2)]
        public string Sigla { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? DataLimiteIsento { get; set; }
        public double? Aliquota { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? Data1 { get; set; }
        [Column(TypeName = "smalldatetime")]
        public DateTime? Data2 { get; set; }
    }
}